name    'counsyl-puppet'
version '0.9.9'
source  'git://github.counsyl.com/dev/puppet-puppet.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Puppet Agent, Forge, and Master'
description 'Installs the Puppet Agent, Forge, and Master'
project_page 'https://github.counsyl.com/dev/puppet-puppet'

dependency 'counsyl/apache', '>= 0.9.2'
dependency 'counsyl/ruby', '>= 0.9.9'
