name    'counsyl-puppet'
version '1.0.0'
source 'git://github.counsyl.com/justin/counsyl-puppet.git'
author 'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Puppet Agent, Forge, and Master'
description 'Installs the Puppet Agent, Forge, and Master'
project_page 'https://github.counsyl.com/justin/counsyl-puppet'

dependency 'counsyl/apache', '>= 1.0.0'
dependency 'counsyl/ruby', '>= 1.0.0'
dependency 'counsyl/sys', '>= 1.0.0'
